You bat away your crown with your walrus flipper when your flipper 
glove accidentally flies off! You've been exposed! Hurt and offended, 
the other walrus deem you a walrus fraud! A statuette is now being 
built in your honor... dishonor! You're now in the middle of a pile 
of sand and rotting fish while the other walrus build around you as 
well as any walrus can. Fiercely patting the ground with their 
non-glove flippers. With a short passing of time, the tide has 
demolished your statue and taken you with it. With their almost 
honorary leader either lost at see or drowned, the walrus go about 
their existence the way they had before as if nothing happened at all.